title: "Joonsup Kim"
author: "Joonsup Kim"
description: "M.S. student in Data Science at Seoul National University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false            # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", url: "/"}
  - {title: "Research", url: "/research/"}
  - {title: "Education", url: "/education/"}
  - {title: "Projects & Honors", url: "/projects/"}
  - {title: "Teaching", url: "/teaching/"}
  - {title: "Video", url: "/video/"}
  - {title: "CV", url: "/cv/"}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:dankim99@snu.ac.kr"}
  - {title: Github, icon: github, url: "https://kimjoonsup.github.io"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
